### ISSUE TITLE
parcels without address numbers

### ISSUE THREAD

**Issue by janmicohio** [codefordayton/daytonreap#26]
process dataset has 2552 addresses without house numbers

**Comment by janmicohio** [comment]
Paula's reply: "nothing can be done about addresses without numbers. This is how the county lists them and that is how they are applied for and why the parcel number rather than the address is the most important piece of data. You would be better off linking the parcel numbers to a map instead of addresses."  Obviously we can't do this. 
The parcel numbers have a constant relationship to the addresses (though in some cases it will be a one-to-many relationship) so we should be able to make a list of all the parcel numbers and associated addresses. Could this be used as a lookup table somehow?

**Comment by janmicohio** [comment]
UPDATE -  I spot checked some of the parcels with missing addresses, and for the ones I checked, it isn't a data entry error - they really don't have street addresses any more. Some, maybe most - of these are actually vacant lots. If we knew this, we might be able to direct people looking for land to this subset The Montgomery  county auditor's office has a program that maps by parcel number. You can try it by doing this:
• Go to www.mcrealestate.org
• click on “property search” in top menu bar • choose “parcel” as your “search by” option • enter the parcel number of one of the properties in our dataset that doesn’t have a street address, then search
• from the results list, double click on the row of the result to get the details • in the right hand column of the “Details” page, there is a very tiny icon and the word “Maps” Click on this and it will launch “GeoBladeWeb” which will show you exactly where the parcel is, plus a window with other details about the property. 
• Go to www.mcrealestate.org
• click on “property search” in top menu bar • choose “parcel” as your “search by” option • enter the parcel number of one of the properties in our dataset that doesn’t have a street address, then search
• from the results list, double click on the row of the result to get the details • in the right hand column of the “Details” page, there is a very tiny icon and the word “Maps” Click on this and it will launch “GeoBladeWeb” which will show you exactly where the parcel is, plus a window with other details about the property. 
_________________________
![screen shot 2015-01-22 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/9003895/5864125/3c08ab62-a24d-11e4-902f-bd467a59cc9a.png)
_______________
Here are some random parcel numbers you can try
R72 05203 0056
R72 07907 0038
R72 01809 0020

**Comment by DavidEBest** [comment]
I didn't think about that... it makes sense, but I didn't realize they would remove the address when a house was destroyed.

**Comment by janmicohio** [comment]
Here's something:
http://www.huduser.org/portal/datasets/usps.html
Not sure if it's relevant, but I like finding stuff like this!

**Comment by DavidEBest** [comment]
Resolved, I think.
