### ISSUE TITLE
Review filters to ensure completeness.

### ISSUE THREAD

**Issue by janmicohio** [codefordayton/daytonreap#27]
Paula said if the county has sold the tax lien, those properties should be excluded from the data we present. Has this already been implemented?

**Comment by DavidEBest** [comment]
Yes, the properties displayed should have filtered all properties with a sold lien or those that aren't eligible for a tax lien.

**Comment by janmicohio** [comment]
Paula doesn't think the filters can possibly be working because the data set is still "way too big." She is eager to come to our next meeting, or even to have some of us to come to her office before then. 
To further complicate matters, she said they have already changed the process since the video, and there are more changes in the works.

**Comment by DavidEBest** [comment]
I'm fairly confident that the filters we have implemented are working. It could be that there are additional filters that are not accounted for, however. Right now, we are filtering to only show those properties marked as eligible, not on a payment plan, and have a parcel id that begins with 'R72'. I'd love to shrink the data set some more, if possible.

Could she describe how the process has changed and how it will change in the near future?

**Comment by DavidEBest** [comment]
Based on the review by Paula, we were not filtering out properties with a delinquency of less than two years.

That is in process now.
