### ISSUE TITLE
Test for Cross Browser Compatibility

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/daytonreap#34]
LotLinker has not received a lot of cross browser compatibility testing. It should be tested in:
- Internet Explorer 9+
- Chrome
- Safari
- Firefox
- iOS' browser
- Android browser

**Comment by DavidEBest** [comment]
I've tested this in Chrome 43.

**Comment by bakerjaandrew** [comment]
Pull Requets #41 should help to make elements Responsive to mobile devices, older devices and browsers are a WIP.

**Comment by bakerjaandrew** [comment]
Browserstack would like to know if we would be able to insert a comment just stating cross browser testing done with the help of browserstack.com, would this be possible?

**Comment by DavidEBest** [comment]
Sure. If it was a useful tool for you, I wouldn't have a problem with a small link in the footer.
