### ISSUE TITLE
add button to static images 

### ISSUE THREAD

**Issue by janmicohio** [codefordayton/daytonreap#47]
![lot links button](https://cloud.githubusercontent.com/assets/9003895/8111656/0397045c-1031-11e5-92d7-fad50acc5f76.jpg)

**Comment by janmicohio** [comment]
remove the Lot LInks logo from the footer
Insert this button directly below the last paragraph on the search tool page and before the data description
Set it to be right justified in that location
Make it a hyperlink to the city of Dayton Lot links page

**Comment by DavidEBest** [comment]
:shipit:
