### ISSUE TITLE
Web Design and User Interface

### ISSUE THREAD

**Issue by bakerjaandrew** [codefordayton/daytonreap#53]
Are we able to start working on concept designs/interfaces to help improve it a tad. I can make the styling changes on my fork to be previewable before pull requests get merged.

[Question]

**Comment by DavidEBest** [comment]
Sure. I'm certainly interested in ways to improve the interface.

I just received the following feedback from Paula - 
>I’m starting to get emails at the new email address from people who are not verifying that the property is eligible first.  They are just sending me emails asking if the property is eligible.  Is there a way to prevent someone from sending an email to that address unless it passes the tool’s eligibility check?  I am trying to reduce the number of inquiries I must respond to and this is starting to look like I’m just adding another method for people to ask for eligibility checks, which is increasing my work.  Is there a way when the tool does find something that it asks the user a question like “do you want to verify whether or not this has been applied for?” and then have a yes or no button for them to push….otherwise the email address won’t come up?

I'm not sure yet the best way to do this, but it seems to me the first approach would be to just improve the verbiage on the page.

**Comment by bakerjaandrew** [comment]
An idea I have to resolve this maybe is only display the email and the verbiage regarding eligible properties once a user has clicked on one. Also maybe changing the color of the text "If the property does not show up in this search tool, then it is not Lot Links eligible at this time."

**Comment by DavidEBest** [comment]
I'd be up for trying both of those options. There was some talk about moving the 'Verify Eligibility with Lot Links' email link into the search results div, with the links to the treasurers site.

**Comment by janmicohio** [comment]
Here is a copy of my reply to Paula, who is not on github. 
_____________________
Paula, I think it would be helpful for us to see what kind of stuff people are 
sending you. could you maybe forward the messages to us for a while so we can 
monitor the behavior of the users? 
 
It sounds like the users are (oh! Surprise!) not reading carefully, if at all. 
But to better understand both the types and scope of the problems, we need to 
see exactly what they are doing. 
 
Maybe we can reinforce some of the points with tweaks to the text, and slow them 
down with a stop sign icon. If they are skimming the page, they will likely stop 
at a stop sign. 
 
Some users will always screw up, but we should be able to influence most of them 
to use it correctly and do the next right thing... 
 
_PROPOSED CHANGE TO TEXT PANEL_______________________________ 
If a property you're interested in does not show up in this search tool, then 
STOP! (Icon of STOP sign)  It is not Lot Links eligible at this time. 
There is no point inquiring further about a property that is not in the Lot 
Linker search results. 
 
When you find a property with this search tool you're interested in, you next 
need to find out if anyone else has already applied for it. 
Carefully copy the address and parcel number from the search result, then send 
that info to lotlinks@daytonohio.gov. 
The Lot Links team will check the lot links applications and send you a 
response.
____________________
Let's do this easy thing first and  see how that goes. 
(she said, fighting the compulsion to overengineer at every opportunity...)

**Comment by bakerjaandrew** [comment]
Alright guys, 
I've started to take a different approach... We can definitely play with this and find the best solution. what I've found to be the simplest and easiest to digest is an FAQ with the main questions being expandable so they're easy to read the titles and expand if you really need the infomation. Please check out daytonreap.baker.ja.andrew.c9.io for an idea, it's still a WIP.

**Comment by janmicohio** [comment]
That's an idea we offered early on, along with a redesign of the city's page- both were rejected. 
Paula would like us to completely automate the process, (not politically possible) This is attractive in part because we are responsive to her needs, whereas getting things approved then changed through the bureaucracy is very slow and difficult. She's told us the process for the program is subject to change soon. (Not the selection criteria - just some of the process) My thought has been that we don't want to be doing this modifying indefinitely, and we are here to do the things that the IT folks can't do and then move on. Customers should come to LotLinker.com, use the tool to get through the initial 4 screening criteria, then they go back to the city site for the next step, further instructions etc. We need to give them enough context to know where they are if they land on us first, and we should give them the info they need to know what the one next step is, and that's about all. 
I do think it's worth putting out the FAQ idea to Paula again. It would be easy to make the text pop-ups etc and have a little if that on the LotLinker page. BTW I also created a checklist at one point - people could print it for each property and have a stepwise reference, maybe even as a flow chart, but because the steps are going to change sometime, that idea was also dismissed. 
We still haven't gotten any actual data on the users. I don't think we should consider all of these anecdotal reports to be meaningful problems  - many of the "problems" are simply beyond the scope of a coding project.

**Comment by bakerjaandrew** [comment]
I believe the expandable FAQs are very easy for the user to digest rather than a wall of text and much more visually pleasing. The FAQ buttons are functional now at the above mentioned URL. I as well think we should have them view the sample. We can push that quickly even with a few more tweaks.

**Comment by janmicohio** [comment]
I agree with you bakerjaandrew - the buttons are way better! 
  
I think it can do without the "FAQ" and just have the question buttons. 
What about making the text in the top paragraphs a little smaller?
What other way could we present the individual drop down info so that the user doesn't end up scrolling down to the point where they can't see the search box any more?

**Comment by DavidEBest** [comment]
This is looking great, @bakerjaandrew!

The text might be a bit easier to read if you increased the width of the left panel, and decreased the margins on the faq entries (which look fantastic!).

As a usability tweak, could you change the cursor to a pointer over the faq titles to indicate that they are clickable?

Again, this is great work!

**Comment by bakerjaandrew** [comment]
Alright @janmicohio I have ditched the FAQ header and made the intro-paragraph a tad smaller. As well I have made the search bar static, while the into-paragraph and FAQ buttons scroll under it when the panel begins to overflow.

@DavidEBest I have changed the margins a bit and added the pointer cursor as well as cleaned up the look a little bit.

Let me know if I've missed anything, I'm starting to move this onto testing in other browsers to ensure the buttons and static search are working and then moving onto centering items for older browsers that don't support flexbox.

**Comment by janmicohio** [comment]
Super excellent, @bakerjaandrew ! 
You didn't miss anything. The tweaking may be nearly at an end... 
• Do you think a faint "X" in the corner of the FAQ buttons would cue users to realize they can click the box again to close the panel they opened? 
• Now I think the size of the text in the drop down panels should match the size of the font in the top paragraph
• The line in the eligibility list about tax lien should say "its lien" istead of "their lien"

**Comment by bakerjaandrew** [comment]
I added the X to signify a close, I've decreased the text to the same size as the intro paragraph, and updated the text in the eligibility paragraph.

I've updated the FAQ panels to expand with-in the FAQ buttons so they seem more related and easier to read.

**Comment by janmicohio** [comment]
PERFECT!   Thank you @bakerjaandrew 

I think we're ready to schedule our formal presentation to the city...
Remember we keep the BETA NOT FOR PRODUCTION banner in place until the formal presentation. 

The city commission meets on Wednesdays, sometimes mornings, sometimes evenings.  An evening meeting will allow more of our membership to attend. The evening meetings occur on the first, third and fifth Wednesdays of the month. I would like the planners and presenters to attend at least one meeting before we present to get a feel for the event and scope out the equipment available. The next evening meeting is July1. If we can go to that one to check it out, then we can ask to be scheduled for the July 15 meeting. 

@DavidEBest ,  @bakerjaandrew,  @dwcaraway   Will this schedule work for you?

**Comment by bakerjaandrew** [comment]
@janmicohio 
I agree an evening meeting would be better, though it depends on the times of these meets as I work in Cincinnati.

**Comment by DavidEBest** [comment]
Same here. I should be able to attend the July 1st one to scope it out.

**Comment by DavidEBest** [comment]
@bakerjaandrew This looks great. One thing I just noticed - 'About' and 'Resources' can be removed from the menu bar.
Other than that, I'd be happy with getting this merged over to the lotlinker.com site. Care to issue a PR?

**Comment by bakerjaandrew** [comment]
@DavidEBest alright I'll remove those, and start to submit a PR. I fulling PR's will be browser support.

**Comment by janmicohio** [comment]
Commission meetings start at 6pm. @bakerjaandrew You wouldn't necessarily need to come on the scouting expedition. So July 1 for scouting it out and July 15 for presentation?

**Comment by bakerjaandrew** [comment]
@janmicohio I should be able to make that and would love to attend if possible.

**Comment by DavidEBest** [comment]
Closing this, because I _think_ this was done with @bakerjaandrew's rework. If you think it is still an open question, feel free to re-open.
