### ISSUE TITLE
Search sluggishness

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/daytonreap#67]
LotLinker has always had a noticable delay in accepting user input & returning search results. This is especially bad for IE, which displays the 'this page is not responding due to a long running script message'.

How can we improve the experience?
Ideally, we:
- remain client-side only
- improve general responsiveness
- get rid of the 'long running script' warning on IE

Open to:
- replacing our typeahead plugin
- indexing more at app startup (including putting a loading/wait screen)
- going to a server-based search (only if absolutely necessary)
- any other clever ideas

**Comment by jlalthoff** [comment]
did this upgrade improve performance any?  I don't have IE or any sluggishness to compare to. 

I did find changing the minLength to 2 in   $("#addressInput").typeahead({
reduced the milliseconds used for the first search by a factor of 10 .

**Comment by DavidEBest** [comment]
It could be better, but that change did improve the results. I've experimented some with changing the input length. That is a good way to improve performance; we need to account for the properties re-appearing on the map when the field is cleared.

**Comment by itopaloglu83** [comment]
After working with Jeff today, we have come to the realization that the site is perpetually searching after typing anything in the search field. I hypotise that this is because of the search index array "markerSearch" is dynamically updated.

**Comment by DavidEBest** [comment]
Good find! 👍

**Comment by itopaloglu83** [comment]
Well, we were wrong. I profiled the website.
Sluggishness comes from the setMarkers() function. 

It is used to update the map according to the search result. However, when the user click on the search box, setMarkers takes 900ms to complete. After the initial character it takes another 400ms to complete. Following keystrokes takes less time due to diminishing results. And then, when there's no result found, setMarkers again sets all the markers and takes 900ms to complete.

**Comment by itopaloglu83** [comment]
This is a issue related to leaflet dependencies. They resolved this issue ([#357](https://github.com/Leaflet/Leaflet.markercluster/issues/357)) with the current version. Could someone please update the following dependencies to their current versions?
"leaflet"
"leaflet.markercluster"
"Leaflet.awesome-markers"

**Comment by DavidEBest** [comment]
Could you try this locally to confirm that it is the problem?

The `bower.json` file defines the versions of the libraries to include. If you update that file and then run `bower install` it should give you the most recent versions. The package search engine at bower.io should contain the version numbers of the most recent versions.

**Comment by itopaloglu83** [comment]
I don't have my development environment setup yet. So, I had to improvise. I confirmed that the solution worked by manually replacing javascript references (leaflet, leaflet.markercluster and leaflet.awesome-markers) in the index.html.

**Comment by DavidEBest** [comment]
Much better... good find with the leaflet dependencies. I've pushed the change to the live LotLinker site. 👍
