### ISSUE TITLE
Add a filter to show newly added properties.

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/daytonreap#76]
As a user, I would like to be able to filter the properties on the map to only see the ones that were added this month.

This is feasible, but it will require a slight modification to the workflow.

To do this, I'd probably:

* update the `scripts/buildjson.py` to open the previous month's file (which isn't saved in systematic way at this point) and try to find each entry in the new file in the old one. If it is not there, then add a new field to the json.
* add a filter toggle on the left panel of the site to show only new properties. This toggle should be tied to the newly added flag.

**Comment by LukeKuenneke** [comment]
I think this is done.
