### ISSUE TITLE
Facilitate the users' ability to determine the current owner of a particular property. 

### ISSUE THREAD

**Issue by janmicohio** [codefordayton/daytonreap#8]
It is often very difficult to determine what entity is responsible for a property. The owner of record may be a trust, a corporation (frequently an LLC), a bank,  or have a business name with no indication of what human - and there is always a human in there somewhere - is currently responsible. Figuring this out requires searching other public records. We can supply links to these sources based on the ownership type so that the user can dig deeper without having to figure out where to look.

**Comment by DavidEBest** [comment]
@janmicohio Is this still a thing we should pursue?
